### ISSUE TITLE
do not treat "file already exists" as an error to prevent error notifications

### ISSUE THREAD

**Issue by superhenne** [fgebhart/zeit-on-tolino#25]
When the .epub file that the script is trying to upload to webreader.mytolino.com already exists, an error is generated (FileExistsError). This leads to error notifications sent out by github. IMO this is not a real error, and should rather be ignored. At least no notification should be generated. Alternatively, there is a way to prevent further executions of the workflow once the upload has been successfully run.

**Comment by fgebhart** [comment]
Thanks for filing this issue. Sounds like an valuable addition to me. I will try to see what it would take to implement this.

**Comment by fgebhart** [comment]
The linked PR implements the requested enhancement. We should be able to verify the impact on Wednesday.
