### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by DominikKuenkele** [fgebhart/zeit-on-tolino#26]
I would like to be able to run the synchronization on a server in a docker container. I already implemented that in my own repository [sync-zeit-to-tolino](https://github.com/DominikKuenkele/sync-zeit-to-tolino) that is based on yours, because your repository is focusing on GitHub Actions. But i think it would still make sense to combine both. I could create a pull request to add some of my code for creating a Dockerfile. But if you think, this shouldn't be part of this repository, I could also create a fork.

**Comment by fgebhart** [comment]
Thanks for reaching out! I agree on reducing code duplication. However I can think of at least one more approach of how this could be implemented.

In `fgebhart/zeit-on-tolino` we could upload the existing functionality to PyPI. In `DominikKuenkele/sync-zeit-to-tolino` you could download the package and use it with your docker setup. Doing so would allow me to keep the docker functionality from my repo and you could reduce the code within your repo probably by a lot.

Furthermore, I could like to your repo as "one more way of running the sync" or something like that.

Let me know what you think. Just want to check out all the possibilities we have.

**Comment by fgebhart** [comment]
However, if the docker setup is just a single/few smallish files, it is probably the easiest way to add it this repo. Could you point me to elaborate on what code would need to be added?

Also, are you aware of a way how we could cover the functionality of the docker setup with automated tests (i.e. github actions)?

**Comment by fgebhart** [comment]
Closing for now, feel free to reopen if needed.
